#version: 2
#updates:
#- package-ecosystem: composer
#  reviewers:
#    - "mqwerty"
#  directory: "/"
#  schedule:
#    interval: "weekly"
#    day: "saturday"
#    time: '04:00'
#    timezone: Europe/Moscow
#  open-pull-requests-limit: 10
