version: '3'
services:
  test:
    build: .
    entrypoint: []
    command: sh -c "cp config.example.php config.php && composer install --no-interaction --no-progress --no-suggest && composer test:unit && composer stan:phan && composer cs:check"
