---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.php: |
    <?php
    return [
      'env' => 'prod',
    ];
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: edmitry/test-github-actions
          name: app
          volumeMounts:
            - name: config
              mountPath: /app/config.php
              subPath: config.php
          readinessProbe:
            httpGet:
              path: /
              port: 2113
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /
              port: 2113
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 10
      volumes:
        - name: config
          configMap:
            name: config
